server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: categoria-service
          uri: lb://categoria-service
          predicates:
            - Path=/categoria/**
        - id: empleado-service
          uri: lb://empleado-service
          predicates:
            - Path=/empleados/**
        - id: ingreso-service
          uri: lb://ingreso-service
          predicates:
            - Path=/ingreso/**
        - id: justificativo-service
          uri: lb://justificativo-service
          predicates:
            - Path=/justificativo/**
        - id: autorizacion-service
          uri: lb://autorizacion-service
          predicates:
            - Path=/autorizacion/**
        - id: planilla-service
          uri: lb://planilla-service
          predicates:
            - Path=/planilla/**
            
